sonhal/chatbot-master/chatsapp/bot/urls.py
from django.conf.urls import url

from django.urls import include, path

from django.contrib.auth.forms import UserCreationForm


from .import views
app_name= 'bot'
urlpatterns = [
	path('', views.help_bot, name='help_bot'),
	
]

sonhal/chatbot-master/chatsapp/chatsapp/urls.py
from django.contrib import admin
from django.urls import include, path



from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.conf.urls.static import static 
from django.conf import settings




urlpatterns = [
	path('admin/', admin.site.urls),
    path('', include('talkbot.urls')),
    path('help/', include('bot.urls')),

]


urlpatterns+=staticfiles_urlpatterns()


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sonhal/chatbot-master/chatsapp/talkbot/urls.py
from django.conf.urls import url

from django.urls import include, path

from django.contrib.auth.forms import UserCreationForm


from .import views



app_name= 'talkbot'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('contact_us/', views.contact_us, name="contact_us"),

    path('member/<int:friend_id>/', views.member, name='member'),
    path('chatroom/<int:chatroom_id>/', views.chatroom, name='chatroom'),
    path('createmessage/<int:chatroom_id>/', views.create_message, name="create"),
]

sonhal/chatbot-master/chatsapp/talkbot/models.py
from django.db import  models
from django.contrib.auth.models import User


# Create your models here.
class Message(models.Model):
    text = models.CharField(max_length=500)
    # So we can see till which chatroom it sends the message.
    chatroom = models.ForeignKey('Chatroom', on_delete=models.CASCADE)
    # See who Sent the Message.
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Create a TimeStamp on the Message.
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}, {}'.format(self.text,self.chatroom)

class Member(models.Model):
    # See Who's Member on the ChatRoom.
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    chatroom = models.ForeignKey('Chatroom', on_delete=models.CASCADE)

    def __str__(self):
        return '{}, {}'.format(self.user,self.chatroom)


class Chatroom(models.Model):
    # See Who Creatade the Room.
    created_by = models.CharField(max_length=50)
    # Name of the Room So we can See if the it Exist.
    name_of_chatroom = models.CharField(max_length=50)

    def __str__(self):
        return '{}, {}'.format(self.created_by,self.name_of_chatroom)


class Upload(models.Model):
    picture = models.ImageField(default=None, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return '{}, {}'.format(self.picture, self.user)

sonhal/chatbot-master/chatsapp/talkbot/forms.py
from django import forms

from .models import Message, Member, Chatroom, Upload

from django.forms import HiddenInput

class CreateMessageForm(forms.ModelForm):
	text = forms.CharField(label='')
	
	class Meta:
		model = Message
		fields = ['text']
		# widgets = {
		# 	'room': forms.HiddenInput(),
		# }

class UploadForm(forms.ModelForm):

	class Meta:
		model = Upload
		fields = ['picture']

sonhal/chatbot-master/chatsapp/talkbot/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .import forms
from .models import Chatroom, Message, Member, Upload
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

from django.contrib.auth.decorators import login_required

#Flash message
from django.contrib import messages



def profile(request):
    # Get all User in dataBase Exclude Admin and the User. Display at html template friend list.
    form = forms.UploadForm()
    users = User.objects.all().exclude(username='admin').exclude(username=request.user)
    upload = Upload.objects.filter(user_id=request.user.id)
    if request.method == 'POST':
        form = forms.UploadForm(request.POST,  request.FILES)
        print('Before Validatiom')
        if form.is_valid():
            media = form.save(commit=False)
            media.user = request.user
            media.save()
            print('adfter SAve')
            return render(request, 'user_profile.html')
    context = {
        'upload': upload,
        'users':users,
        'form': form
    }
    return render(request, 'user_profile.html', context)


# Works
def signup_view(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            print('Created a new User')
            login(request, user)
            return redirect('talkbot:profile')
    context = {
        'form':form
    }
    return render(request, 'signup.html', context)



# Works
def logout_view(request):
        logout(request)
        return redirect('talkbot:login')


# Works
def contact_us(request):
    return render(request, 'contact_us.html')


# Works 
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            print('form is valid')
            user = form.get_user()
            login(request, user)
            # Redirect User after Login in.
            if 'next' in request.POST:
                return redirect(request.POST.get)
            else:
                return redirect('talkbot:profile')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form':form})


# Works
def member(request, friend_id):
    # Check if User and his Friend are Members to a Chatroom.
    memberroom = Chatroom.objects.filter(member__user=request.user).filter(member__user=friend_id)
    print('Before If Statment')
    print(friend_id)
    if len(memberroom) == 0:
        print('Empty list.')
        create_room = Chatroom(created_by=request.user, name_of_chatroom='MushroomHunt')
        create_room.save()
        # Get the last room in the list that we just created.
        new_room = Chatroom.objects.last()
        # Push in Members to the  last Room we just created.
        # Pushed my ID First
        member = Member(chatroom=new_room, user=request.user)
        # Storing Friends ID in Member.

        member_friend = Member(chatroom=new_room, user_id=friend_id)
        member.save()

        print('roomSaved and past the if statment.')
        member_friend.save()
        #Flas Message That says it creatade a room.
        messages.add_message(request, messages.SUCCESS, 'Enjoy your First Conversation')
        return redirect('talkbot:chatroom', chatroom_id=new_room.id)
    else:
        print(' Not Empty')
        # Get the list of members.
        exist = Chatroom.objects.filter(member__user=request.user).filter(member__user=friend_id)
        # Loop around to see what id is on the chatroom.
        for i in exist:
            chatroom = Chatroom.objects.filter(member__user__id=friend_id).filter(pk=i.id).first()
            if chatroom != None:
                break
        return redirect('talkbot:chatroom', chatroom_id=chatroom.id)


def chatroom(request, chatroom_id):
    chatroom = Chatroom.objects.get(pk=chatroom_id)
    texts = Message.objects.all().filter(chatroom=chatroom_id)
    form = forms.CreateMessageForm()
    context = {
        'chatroom': chatroom,
        'texts': texts,
        'form': form,
    } 
    return render(request, 'chatroom.html', context)

# Private Chatroom
def create_message(request, chatroom_id):
    form = forms.CreateMessageForm()
    chatroom = get_object_or_404(Chatroom, pk=chatroom_id)
    if request.method == 'POST':
        form = forms.CreateMessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.user = request.user
            message.chatroom = chatroom
            message.save()
            return redirect('talkbot:chatroom', chatroom_id=chatroom_id)
    context = {
        'form':form
    }
    return render(request, 'chatroom.html', context)  

sonhal/chatbot-master/chatsapp/talkbot/templates/base.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en" class="h-100">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'style.css' %}">


  <title>{% block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column h-100">
  <main role="main" class="flex-shrink-0">

    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
      <a class="navbar-brand" href="{% url 'talkbot:profile' %}">CHAT</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'talkbot:profile' %}">Home</a>
          <a class="nav-item nav-link" href="#">Public Chatroom</a>
          <a class="nav-item nav-link" href="{% url 'bot:help_bot' %}">HelpCenter </a>
          <a class="nav-item nav-link" href="/contact_us/" >ContactUs </a>

            {% if user.is_authenticated %}

            <a class="nav-item nav-link" href="{% url 'talkbot:logout' %}">Logout </a>
            {% else %}
                    
            <a class="nav-item nav-link" href="{% url 'talkbot:login' %}">Login</a>

            {% endif %}

            <a class ="nav-item nav-link"> {{user.username}} is Online</a>

        </div>
    </nav>


    


  </main>

  <footer class="footer mt-auto bg-dark py-1">
    <div class = "container text-white">
      <div class = "row">
        <div class = "col-md-4">
          <h3><b>CHAT</b></h3>
        </div>
        <div class = col-md-4>
          <ul class = "list-unstyled">
            <li class = "text-muted mb-3">ABOUT US</li>
            <li><a href="{% url 'talkbot:contact_us' %}">Who We Are</a></li>
          </ul>
        </div>
        <div class = col-md-4>
          <ul class = "list-unstyled">
            <li class = "text-muted mb-3">CONTACT</li>
            <li>chat@chat.com</li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

</body>

</html>


    {% endblock %}

    {% block content %}{% endblock %}

sonhal/chatbot-master/chatsapp/talkbot/templates/chatroom.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Member Page {% endblock %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<h2> ChattRooom {{ chatroom.name_of_chatroom }} </h2>

<div class="container">
    <h3> Creater of the group {{ chatroom.created_by }}</h3>


    {% if messages %}
    <ul class="messages">
        {% for msg in messages %}
        <li> 
            <div class="alert alert-success" role="alert">
                {{msg.message}}
            </div>
        </li>
        {% endfor %}
    </ul>
    {% endif %}



    <div class="messagebox overflow-auto">
        <ul class="list-group">
            {% for text in texts %}
            <li class="list-group-item list-group-item-secondary">{{text.user}}: {{text.text}} </li>
            {% endfor %}
        </ul>
    </div>


    <!-- write message -->

    <form class="form-inline" method="post" action="{% url 'talkbot:create' chatroom_id=chatroom.id %}">

        <div class="form-row w-100">
            {% csrf_token %}
            <div class="form-group col-md-12">
                <div class="message-text-input">
                    {{ form|crispy }}
                </div>
                <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </div>              
    </form>
</div>

{% endblock %} 

sonhal/chatbot-master/chatsapp/talkbot/templates/contact_us.html
{% extends 'base.html' %}
{% block title %} Contact Us {% endblock %}
{% block content %}
	<link rel="stylesheet" type="text/css" href="stylish.css">
	<div class="row row_b">
		<div class="col-md-2">
			<h6>What's happening?</h6>
			<ul>
				<li>Friends</li>
				<li>Messages</li>
				<li>Groups</li>
				<li>Chatbot</li>
			</ul>
			<br>
			<h5>Contact Us!</h5>
			<br>
			<ul>
				<li>Phone: 058 739 5345</li>
				<li>Address: 35 Ahad Ha'am, Tel Aviv, Israel</li>
				<li>Email: alyosav@aya.com</li>
				<li>Phone: 058 739 5345</li>
				<li>Fax: 058 739 5345</li>
			</ul>
		</div>
		<div class="col-md">
			<h1>Yossi Kahyko</h1>
			<img src="https://vignette.wikia.nocookie.net/hanna-barbera/images/2/24/Johnny_Bravo.jpg/revision/latest?cb=20120423033926" alt="Trulli" width="150">
			<h6 class="mt-5">Born in Stockholm, Sweden, Yossi is a world class leading web developer. He has three olympic gold medals. One in snowboarding, one is figure skating, and another in swimming. At the age of 27 he began Developers Institute Bootcamp in Tel Aviv, Israel where he now resides.  Along with his exceptional athetic ability, he also enjoys painting still lifes, improving his chess skills, and is currently writing a book titled "Don't Hate me because I am handsome. Hate me because I am better than you".</h6>
		</div> 
		<div class="col-md">
			<h1>Alan Tanz</h1>
			<img src="https://scontent.ftlv1-2.fna.fbcdn.net/v/t1.0-9/51086978_10108210090424872_9015544436326662144_o.jpg?_nc_cat=110&_nc_ht=scontent.ftlv1-2.fna&oh=9aa83aeb3e4c818ba4a8ce2411101509&oe=5D3768E9" alt="Trulli" width="200">
			<h6 class="mt-4">Born in New York City, Alan is a world class leading web developer. He has won the Eurovision Song contest twice for Israel (1998, 2018). At the age of 31 he began Developers Institute Bootcamp in Tel Aviv, Israel.  Along with his making music, he is also a licensed paramedic and speaks English, French, German, Spanish, Hebrew, Turkish, and Korean.</h6>
		</div> 
		<div class="col-md">
			<h1>Avi Guner</h1>
			<img src="https://i.ytimg.com/vi/ofSydaFRDAo/hqdefault.jpg" alt="Trulli" width="300">
			<h6 class="mt-3">Born in Istanbul, Turkey, Avi is a world class leading web developer. At the age of 21 he finished studies at Yeshiva and became the chief rabbi of Ra'anana, Isreal. At the age of 25 he began Developers Institute Bootcamp in Tel Aviv, Israel.  Along with his teaching young Jewish men about Tanach, Talmud, and Kaballah his rabbinic commentary on The Shulchan Aruch has been included in countless anthologies.</h6>
		</div> 

</body>
</html>
{% endblock %}

sonhal/chatbot-master/chatsapp/talkbot/templates/footer.html
<!--



<footer class="footer">
    <div class="row" id="borders">

        <div class="col-md-4">
             <h5><b>CHAT</b></h5>
            <p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            </p>
        </div>

        <div class="col-md-4">
            <h5><b> Who We Are </b></h5>
            <p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
            </p>
        </div>

        <div class="col-md-4">
            <h5><b> Chat@chat.com </b></h5>
            <p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
            </p>
        </div>
        
    </div>







</footer>

-->

sonhal/chatbot-master/chatsapp/talkbot/templates/help_center.html
{% extends 'base.html' %}
{% block title %} Help Center {% endblock %}
{% block content %}
<h2> Help Center </h2>

	<div class="container">
		<h3> Talk to one of our Bots</h3>



     <div class="messagebox">
        <ul class="list-group">

	        <li class="list-group-item list-group-item-secondary">Answer<li>

        </ul>
      </div>

	</div>

{% endblock %} 

sonhal/chatbot-master/chatsapp/talkbot/templates/login.html
{% extends 'base.html' %}
{% block title %} Login  {% endblock %}
{% block content %}


    <div class="row justify-content-center mt-5">

        <div class="col-4">

            <h3>Login</h3>

            <hr>

            <form method="post">

                {%csrf_token%}

                {{form.as_p}}

                <br>

                <button type= 'submit' value="Login" class = "btn btn-danger">Login</button>
                <p> No Account No Worries Create one Here! </p>
                <a href="{% url 'talkbot:signup' %}"> Create </a>
            </form>

        </div>

    </div>



{% endblock %}

sonhal/chatbot-master/chatsapp/talkbot/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <a style="color:red" href="{% url 'talkbot:profile' %}"><b> Chat with the World </b></a>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar">
      <a class="nav-item nav-link active" href="{% url 'talkbot:profile' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'talkbot:chatroom' chatroom_id=75%}">Public Chatroom</a>
      <a class="nav-item nav-link" href="{% url 'bot:help_bot' %}">HelpCenter </a>
      <a class="nav-item nav-link" href="/contact_us/" >ContactUs </a>
      <a href="#" class="ml-2" style="color:green"> {{user.username}} is Online</a>

{% if user.is_authenticated %}

<a class="nav-item nav-link" href="{% url 'talkbot:logout' %}">Logout </a>
{% else %}
        
<a class="nav-item nav-link" href="{% url 'talkbot:login' %}">Login</a>

{% endif %}

    </div>
  </div>
</nav>

sonhal/chatbot-master/chatsapp/talkbot/templates/signup.html
{% extends 'base.html' %}
{% block title %} Sign  Up {% endblock %}
{% block content %}

	<h1> Sign Up </h1>
		<form action="{% url 'talkbot:signup' %}" method="post">
		    {{ form }}
		    {% csrf_token %}
		    <input type="submit" value="Submit">
		</form>

{% endblock %}

sonhal/chatbot-master/chatsapp/talkbot/templates/user_profile.html
{% extends 'base.html' %}
{% block title %} Index Page {% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="stylish.css">

<div class="row row_b">
	<div class="col-md-2">
		<h6>What's happening with your friends?</h6>
		<ul class="profile">
			<li>Friends</li>
			{% for user in users %}
			<a href="{% url 'talkbot:member' friend_id=user.id %}"> <li><p> {{user.username}} </p></li></a>
			{% endfor %}
		</ul>
	</div>
	<div class="col-md">
			{% for pic in upload %}


	<img src="{{ pic.picture.url }}" width="200">

	{% endfor %}
		<h4> Welcome:  {{user.username}} </h4>
		<h2>Profile Pic</h2>
		<h3> Add text about me About me</h3>
		<h3> Help Center Ask Question Here if you need help!</h3>

		<div>
			<form method="post" action="{% url 'talkbot:profile' %}" enctype="multipart/form-data">
				{% csrf_token %}

				{{form}}
				<input type='submit' value="Upload">
			</form>
		</div>
	</div>
	<div class="col-md-2">
		<h6>Tell us about you!</h6>
		<ul class="profile">
			<li>Change Picture</li>
			<li>Update Information</li>
			<li>Add video</li>
			<li>History</li>
		</ul>
	</div>


</div>  




{% endblock %} 