chatsapp/talkbot/urls.py
from django.conf.urls import url

from django.urls import include, path

from django.contrib.auth.forms import UserCreationForm


from .import views



app_name= 'talkbot'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('contact_us/', views.contact_us, name="contact_us"),

    path('member/<int:friend_id>/', views.member, name='member'),
    path('chatroom/<int:chatroom_id>/', views.chatroom, name='chatroom'),


    path('profile/delete/<int:chatroom_id>/', views.delete_message, name='delete_message'),

    path('update_profile_info/', views.update_profile_info, name='update_profile_info'),
    path('delete_profile_info/', views.delete_profile_info, name='delete_profile_info'),

    path('create_message/<int:chatroom_id>/', views.create_message, name="create"),
    path('create_post/', views.createpost, name="createpost"),
    path('create_like/<int:post_id>/', views.create_like, name="create_like"),

    path('allpostroom/', views.allpostroom, name="allpostroom"),

    # Find Friend
    path('find_friend/', views.find_friend, name="find_friend"),
    # View your friends wall
    path('yourfriendwall/<int:friend_id>/', views.friend_view, name="friend_view"),

    # Takes him to the game room.
    path('game_room/', views.game_room, name="game_room"),
    path('roll_dice/', views.roll_dice, name="roll_dice"),
    path('game_room_outcome/<int:number>/', views.game_room_outcome, name="game_room_outcome"),
]

chatsapp/talkbot/templates/all_post_room.html
{% extends 'base.html' %}
{% block title %}  All Post Room  {% endblock %}
{% block extra_head %}
{% load static %}
<meta name="description" content="See your own profile easly at django chat" >
<link rel="stylesheet" href="{% static 'stylefolder/all_posts_room.css' %}">
{% endblock %}
{% block content %}

<div class="main_container">
	{% for post in allposts %}
		<div class="post_container">
			<div class="view_friend_container">
				<a href="{% url 'talkbot:friend_view' friend_id=post.user.id %}"> View page </a>
			</div>
			<div class="image_post_container">
				<img src="{{post.image.url}}" alt="post image">
			</div>
			<div class="content_container">
				<h5 class="card-title"> {{ post.title }} </h5>
				<p class="card-text"> {{ post.body }} </p>
			</div>
			<div class="label_container">
				<span> Created at: {{ post.date_created }} <b class="mr-2">by</b>{{ post.user.username}}</span>
				<span class="like_container">{{ post.like }} </span>
				<a href="{% url 'talkbot:create_like' post_id=post.id%}" class="like_button">Like </a>
			</div>
		</div>
	{% endfor %}
</div>
{% endblock %} 

chatsapp/talkbot/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'style.css' %}">


	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	{% block extra_head %}{% endblock %}
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	{% include 'navbar.html'  %}
	{% block content %}{% endblock %}


	{% include 'footer.html' %}

</body>
</html>

chatsapp/talkbot/templates/chatroom.html
{% extends 'base.html' %}
{% block title %} Chatroom {% endblock %}
{% block extra_head %}
{% load static %}
<meta name="description" content="Chat with your Friend at django chat" >
<link rel="stylesheet" href="{% static 'stylefolder/chatroom.css' %}">
{% endblock %}
{% block content %}

 {% if messages %}
    <div class="messages">
        {% for msg in messages %}
            <div class="alert alert-success" role="alert">
                {{msg.message}}
            </div>
        {% endfor %}
    </div>
{% endif %}
<div class="chat_container">
    <div class="chat_screen">
       {% for text in texts %}
            <div class="text_container">   
                 <b>{{text.user}}:</b> <p >{{text.text}}</p> 
            </div>
        {% endfor %}
    </div>
    <div class="chat_desk">
        <form class="message-text-input" method="post" action="{% url 'talkbot:create' chatroom_id=chatroom.id %}">
            {% csrf_token %}
            {{form}}
            <input type='submit' value="create">
        </form>
    </div>
    <div class="button_container">
        <a href="{% url 'talkbot:delete_message' chatroom_id=chatroom.id %}" class="delete_message"> Delete all your messages </a>
        <a href="{% url 'talkbot:profile' %}" class="back_to_profile_button"> Back to profile </a>
    </div>
</div>
<script>
let user = "{{request.user}}"
let text_container = document.querySelectorAll('.text_container');
console.log(text_container);
text_container.forEach((container) =>{
    if(container.firstElementChild.innerHTML.includes(user)){
        container.firstElementChild.style.color = 'green';
    };
});
</script>
{% endblock %} 

chatsapp/talkbot/templates/contact_us.html
{% extends 'base.html' %}
{% block title %} Conctact page {% endblock %}
{% block extra_head %}
{% load static %}
<meta name="description" content="Contact me" >
<link rel="stylesheet" href="{% static 'stylefolder/contact_page.css' %}">
{% endblock %}
{% block content %}
<div class="wrapper">
	<div class="container">
		<h1> Yossi Kayhko </h1>
		<img src="https://vignette.wikia.nocookie.net/hanna-barbera/images/2/24/Johnny_Bravo.jpg/revision/latest?cb=20120423033926" alt="Johnny_Bravo" width="150" class="image_bravo">
		<hr>
		<p>
			I'm passionate about technologies and programming. 🚀
			I'm a hard worker and I have a strong resilience at work.
			<br>
			<b>Programing Languages:</b>
			<br>
			-Javascript
			- React
			- DOM
			- Python
			- Web (Front & Back)
			- JSON / Database / SQL
			- Django/Flask
			- Git
			<br>
			<b>Marketing skills:</b>
			<br>
			- Google Search Console
			- Google Analytics 
			- SEO
			- PPC
			<br>
			<b>Languages</b>
			🇸🇪 - Swedish (native)
			🇬🇧 - English (fluent)
			🇮🇱 - Hebrew (very good level)
		</p>
		<div class="label_container_bottom">
			<p> Phone: 050-2100719 </p>
			<p> Email: yossi.kayhko@gmail.com</p>
			<p> Facebook: Yossi Käyhkö </p>
		</div>
	</div>

	<div class="start_spinner_button">
		Click here!
	</div>
</div>
<script>
	let image = document.querySelector('.image_bravo');
	setInterval(function(){ image.style.transform = 'scale(1.10)'; }, 600);
	setInterval(function(){ image.style.transform = 'scale(1.00)'; }, 800);
	let button = document.querySelector('.start_spinner_button').addEventListener('click',  spin );
	function spin(){
		let x = 5;
		let container = document.querySelector('.container');
		let button = document.querySelector('.start_spinner_button');
		console.log(button)
		button.style.display = 'none';
		container.style.transform = "rotate("+x+"deg)";
		let timer = setInterval( () =>{
			if(x !== 360){
				x++;
				container.style.transform = "rotate("+x+"deg)";
			} else if (x === 360){
				clearInterval(timer);
				button.style.display = 'block';
			}
		},5);
	}
</script>
{% endblock %}

chatsapp/talkbot/templates/createpost.html
{% extends 'base.html' %}
{% block title %} CreatePost Page {% endblock %}
{% block content %}
<h1> Create Post </h1>


	<div class="container">
    	<form class="site-form" method="post" enctype="multipart/form-data">
    			{% csrf_token %}

    			{{form}}
    			<input type='submit' value="Post">
    	</form>
    </div>



{% endblock %} 

chatsapp/talkbot/templates/find_friend.html
{% extends 'base.html' %}
{% block title %} Profile Page {% endblock %}
{% block content %}


<div class="container">
		<h3> We found The user </h3>
		<div class="row">
				<div id="found_person" class="card mt-2" style="width: 18rem;">
					<img src="{{ friend_profile.profile_image.url }}" class="card-img-top" alt="Broken Face" style="width:200px; height:200px;">
				  	<div class="card-body">
				    	<h5 class="card-title"> {{ friend_profile.name }} </h5>
				    	<p class="card-text"> {{ friend_profile.description }}.</p>
				    	<a href="{% url 'talkbot:friend_view' friend_id=friend_profile.user_id %}" class="btn btn-primary"> Visit Profile </a>
				  </div>
				</div>
		</div>



<div class="row">
		{% for user in user_profiles %}
		<div id ="searchbox" class="card mt-2 mr-3" style="width: 18rem;">
			<img src="{{ user.profile_image.url }}" class="card-img-top" alt="Broken Face" style="width:200px; height:200px;">
		  	<div class="card-body">
		    	<h5 class="card-title"> {{ user.name}}</h5>
		    	<p class="card-text">{{ user.description }}.</p>
		    	<a href="{% url 'talkbot:friend_view' friend_id=user.user_id %}" class="btn btn-primary"> Visit Profile </a>
		  </div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %} 

chatsapp/talkbot/templates/footer.html
<!-- <footer style="position: fixed; bottom: 0; left: 0; right: 0;">
    <div class="row">
                <form method="post">
            {% csrf_token %}

            {{form_question}}
            <br>
            <input type='submit' value="Ask"  class="btn btn-primary btn-lg">
        </form>

        
    </div>

</footer>

 -->

chatsapp/talkbot/templates/friend_view.html
{% extends 'base.html' %}
{% block title %} Friend Page {% endblock %}
{% block extra_head %}
{% load static %}
<meta name="description" content="See your Friend profile at django chat" >
<link rel="stylesheet" href="{% static 'stylefolder/friend_view.css' %}">
{% endblock %}
{% block content %}
<h3 class="navbar bg-success" style="width:450px; color:white;"> You are viewing your friend page </h3>
<div class="body_container_flex">
	<div class="block_push">
	</div>
{% for person in profile_friend %}
	<div class="main_content_container">
		<div class="profile_container">
			<div class="user_profile_head_banner">
				<div class="user_image_container">
					<img class="profile_img" src="{{ person.profile_image.url }}">
				</div>
				<div class="user_content_profile_container">
					<ul>
						<li>Name:{{person.name}} {{person.lastname}} </li>
						<li> Age: {{person.age}}</li>
						<li>City: {{person.city}}</li>
					</ul>
					<div class="user_description_container">
						{{person.description}}
					</div>
					<label style="color:red" class="mt-2"> Last Login: {{person.user.last_login}} </label>
				</div>
			</div>
			<div class="start_chat_container">
				<a href="{% url 'talkbot:member' friend_id=person.user.id %}"> Send a message </a>
			</div>
    		<div class="bottom_main_container">
    			<div class="history_post_container">
    				{% for post in posts %}
    				<div class="post_container">
						<div class="left_side">
							<div class="post_image_container">
								<img src="{{ post.image.url }}">
							</div>
						</div>
						<div class="right_side">
							<h4>{{post.title}}</h4>
							<p>{{post.body}}</p>
							<span>Created at: {{ post.date_created }} by {{ post.user.username}}</span>
							<div class="button_container">
								 <p class="totalLikes_container">Total Likes {{ post.like }}</p> 
								 <a href="{% url 'talkbot:create_like' post_id=post.id %}" class="createLike_container">Like </a>
							</div>
						</div>
    				</div>
    				<hr>
    				{%endfor%}
    			</div>
    		</div>
		</div>
	</div>
{% endfor %}
	<div class="sidebar_container">
		<div class="update_container">
			<a href="{% url 'talkbot:update_profile_info' %}"> Update Information</a>
		</div>
		<div class="friend_container">
			<h4> People Around the World</h4>
			<hr>
			{% for friend in friends %}
				<div class="mini_friend_container">
					<div class="friend_image_container">
						<img src="{{friend.profile_image.url}}">
					</div>
					<div class="friend_content_container">
						<ul>
							<p>{{friend.name}}</p>
							<p>{{friend.age}}</p>
							<p>{{friend.city}}</p>
						</ul>
					</div>
					<div class="text_friend_container">
						<a href="{% url 'talkbot:friend_view' friend_id=friend.user.id %}"> 
							<div class="button_to_friend">
								View 
							</div>
						</a>
						<a href="{% url 'talkbot:member' friend_id=friend.user.id %}"> 
							<div class="button_to_friend">
								Chat
							</div>
						</a>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
</div>
<a href="{% url 'talkbot:profile' %}"> Go Back To Your Profile </a>

{% endblock %}

chatsapp/talkbot/templates/game_room.html
{% extends 'base.html' %}

{% block title %} Game Room {% endblock %}
{% block content %}
	<h3 class="navbar bg-success" style="width:500px; color:white;"> Play a little game with your friend. </h3>
 

	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<p> User </p>
				<p> Outcome of dice: <b> {{ number }} </b> </p>
				<p> Scores </p>
				<a class="btn btn-success" href="{% url 'talkbot:roll_dice' %}" role="button">Play</a>
			</div>

			<div class="col-sm-6">
				<p> Friend </p>
				<p> Outcome of dice </p>
				<p> Scores </p>
				<a class="btn btn-success" href="#" role="button">Play</a>
			</div>
		</div>
	</div>

{% endblock %}

chatsapp/talkbot/templates/login.html
{% extends 'base.html' %}
{% block title %} Login  {% endblock %}
{% block content %}
{% load static %}
<div class="main_container">
    <div class="left_side">
        <div class="left_side_wrapper">
            <h1 class="mt-4"> Welcome To ChatBot </h1>
            <div class="login_container">
                <form class="login_form" method="post">
                    {%csrf_token%}
                    {{loginForm.as_p}}
                    <button type= 'submit' value="Login" name="loginForm" class="login_button">Login</button>  
                </form>
            </div>
            <hr>
            <h3> No Account ? </h3>
            <p> Feel free to create one </p>
            <div class="createAccForm_container">
                <form class="createAccForm" method="post">
                    {{ createAccForm }}
                    {% csrf_token %}
                    <input type="submit" name="createAccForm" value="Submit" id="createAccForm_button">
                </form>
            </div>
        </div>
    </div>
    <div class="right_side">
        <h4 style="text-align:center;" class="mt-3"> Users on the platform </h4>
        <div class="user_container mt-5">
            {% for profile in profiles %}
                <a href="{% url 'talkbot:friend_view' friend_id=profile.user.id %}">
                    <div class="user_wrapper">
                        <div class="image_container">
                            <img src={{profile.profile_image.url}}>
                        </div>
                        <div class="user_content">
                           <p>{{ profile.name }}</p>
                           <p>{{ profile.age }}</p>
                           <p>{{ profile.city }}</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
        <div class="github_container">
            <a href="https://github.com/Yoskele/" target="_blank">
                <img src="{% static 'github.png' %}">
                <b> Yoskele's portfolio</b>
            </a>
        </div>
    </div>
</div>
<script>
let timer = setInterval( () =>{
    let container = document.querySelector('.user_container');
    let clone = container.firstElementChild.cloneNode(true);
    container.appendChild(clone);
    container.firstElementChild.remove();
},3500)
// console.log('this is last', container.lastElementChild)

</script>
{% endblock %}

chatsapp/talkbot/templates/navbar.html
<nav class="navbar navbar-dark  navbar-expand-lg" id="navbar_container">
  <a class="navbar-brand mr-5"  href="{% url 'talkbot:profile' %}">Django Chat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
       <a href="{% url 'talkbot:chatroom' chatroom_id=1%}">Public Chatroom</a>
       <a href="{% url 'talkbot:allpostroom' %}"> All Post Room </a>
       <a href="{% url 'bot:help_bot' %}">HelpCenter </a>
       <a href="/contact_us/" >ContactUs </a>
       <a href="#" class="ml-2" style="color:green"> {{user.username}} is Online</a>
       {% if user.is_authenticated %}
        <a href="{% url 'talkbot:logout' %}">Logout </a>
      {% else %}
        <a href="{% url 'talkbot:login' %}">Login</a>
      {% endif %}
    </div>
  </div>  
</nav>

chatsapp/talkbot/templates/profile_update.html
{% extends 'base.html' %}
{% block title %} Profile Update Page {% endblock %}
{% block content %}


<div class="container">
  <form class="site-form" method="post" action="{% url 'talkbot:update_profile_info' %}" enctype="multipart/form-data">
    {% csrf_token %}

    {{form}}
    <input type='submit' value="Save">
  </form>

  <a href="{% url 'talkbot:delete_profile_info' %}"> To Delete the Previous infomartion about you Click Here </a>
</div>

</body>
</html>

{% endblock %} 

chatsapp/talkbot/templates/signup.html
{% extends 'base.html' %}
{% block title %} Sign  Up {% endblock %}
{% block content %}

<!-- 	<h1> Sign Up </h1>
	<div class="row justify-content-center">
		<form class="site-form" action="{% url 'talkbot:signup' %}" method="post">
		    {{ form }}
		    {% csrf_token %}
		    <input type="submit" value="Submit">
		</form>
	</div> -->

{% endblock %}

chatsapp/talkbot/templates/user_profile.html
{% extends 'base.html' %}
{% block title %} Profile Page {% endblock %}
{% block extra_head %}
{% load static %}
<meta name="description" content="See your own profile easly at django chat" >
<link rel="stylesheet" href="{% static 'stylefolder/user_profile.css' %}">
{% endblock %}
{% block content %}
{% if messages %}
    <div class="messages">
        {% for msg in messages %}
            <div class="alert alert-success" role="alert">
                {{msg.message}}
            </div>
        {% endfor %}
    </div>
{% endif %}
<div class="body_container_flex">
	<div class="block_push">
	</div>
	{% for person in profile %}
		<div class="main_content_container">
			<div class="profile_container">
				<div class="user_profile_head_banner">
					<div class="user_image_container">
						<img class="profile_img" src="{{ person.profile_image.url }}">
					</div>
					<div class="user_content_profile_container">
						<ul>
							<li>Name:{{person.name}} {{person.lastname}} </li>
							<li> Age: {{person.age}}</li>
							<li>City: {{person.city}}</li>
						</ul>
						<div class="user_description_container">
							{{person.description}}
						</div>
						<label style="color:red" class="mt-2"> Last Login: {{user.last_login}} </label>
					</div>
					<h5> Create a Post </h5>
				</div>
				<br>
				<form class="createpost_form" method="post" enctype="multipart/form-data">
	    			{% csrf_token %}
	    			{{createPost}}
	    			<input type='submit' value="Post" class="post_button">
	    		</form>
	    		<div class="bottom_main_container">
	    			<div class="history_post_container">
	    				{% for post in posts %}
	    				<div class="post_container">
							<div class="left_side">
								<div class="post_image_container">
									<img src="{{ post.image.url }}">
								</div>
							</div>
							<div class="right_side">
								<h4>{{post.title}}</h4>
								<p>{{post.body}}</p>
								<span>Created at: {{ post.date_created }} by {{ post.user.username}}</span>
								<div class="button_container">
									 <p class="totalLikes_container">Total Likes {{ post.like }}</p> 
									 <a href="{% url 'talkbot:create_like' post_id=post.id %}" class="createLike_container">Like </a>
								</div>
							</div>
	    				</div>
	    				<hr>
	    				{%endfor%}
	    			</div>
	    		</div>
			</div>
		</div>
	{% endfor %}
	<div class="sidebar_container">
		<div class="update_container">
			<a href="{% url 'talkbot:update_profile_info' %}"> Update Information</a>
		</div>
		<div class="friend_container">
			<h4> People Around the World</h4>
			<hr>
			{% for friend in friends %}
				<div class="mini_friend_container">
					<div class="friend_image_container">
						<img src="{{friend.profile_image.url}}">
					</div>
					<div class="friend_content_container">
						<ul>
							<p>{{friend.name}}</p>
							<p>{{friend.age}}</p>
							<p>{{friend.city}}</p>
						</ul>
					</div>
					<div class="text_friend_container">
						<a href="{% url 'talkbot:friend_view' friend_id=friend.user.id %}"> 
							<div class="button_to_friend">
								View 
							</div>
						</a>

						<a href="{% url 'talkbot:member' friend_id=friend.user.id %}"> 
							<div class="button_to_friend">
								Chat
							</div>
						</a>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %} 